language: java
jdk:
  - oraclejdk8
# By default TravisCi will call gradlew check'
# script:

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  # webhooks:
  email: false
# services:

